AT-3791 Deprecating setup.py
up42/up42-py pull request #482
Opened 2023-10-20 12:10 UTC by andher1802

(insert scope and description here)

Items:
* [ ] Ran test & live-tests
* [ ] Implemented (new) unit tests
* [ ] Removed credentials
* [ ] Removed argument pointing to staging
* [ ] Updated [documentation](sdk.up42.com)

For release:
* [ ] Bumped version
* [ ] Added changelog
* [ ] Updated announcement banner

2023-10-20 12:23 UTC, dustgalactic commented on README-dev.md
> +3. Create a `config.json` file and fill in the [project credentials](https://docs.up42.com/developers/authentication#step-1-find-project-credentials).
@andher1802 There's a PR that will remove the mentions of project credentials from the DocHub page, see https://up42.atlassian.net/browse/DOC-789. Let's link this page instead: https://sdk.up42.com/authentication/

2023-10-23 07:38 UTC, janchrizz commented
Suggestion: update the PR's description (rn it looks like a placeholder)

2023-10-23 07:56 UTC, dustgalactic commented on README-dev.md
> +3. Create a `config.json` file and configure according to the [authentication guidelines](https://sdk.up42.com/authentication/)
```suggestion
3. Create a `config.json` file and configure according to the [authentication guidelines](https://sdk.up42.com/authentication/).
```

2023-10-23 10:11 UTC, dustgalactic approved these changes

2023-10-23 13:27 UTC, seedlit reviewed
left a comment.
stupid question - removing `setup.py` will have no impact on conda release right?

2023-10-24 14:44 UTC, javidq requested changes

2023-10-24 14:44 UTC, javidq commented on Makefile
>  install[dev]:
The following steps need to change as well:
1. install needs to change to use poetry
2. pytest - to switch to poetry
3. e2e - to switch to poetry. Do we actually need this as a separate step?
4. serve - better to switch to poetry to make sure that it runs with the specified dependencies
5. gh-pages - poetry
6. package + upload - twine is not needed anymore, switch to poetry

2023-10-24 14:44 UTC, javidq commented on README-dev.md
>  make install[dev]
why not poetry install?

2023-10-24 14:44 UTC, javidq commented on README-dev.md
>  4. Test it in Python! This will authenticate with the UP42 Server and get the project information.
In run tests we propose to developers to run live tests, let's drop that

2023-10-24 14:44 UTC, javidq commented on setup.py
> -    version=parent_dir.joinpath("up42/_version.txt").read_text(encoding="utf-8"),
Our poetry setup uses static version while this one uses external versioning. We either need to use this file in the poetry or drop it completely

2023-10-24 14:44 UTC, javidq commented on setup.py
> -    author_email="support@up42.com",
missing in pyproject.toml

2023-10-24 14:44 UTC, javidq commented on setup.py
> -    license="MIT",
We need to change pyproject, otherwise it doesn't have a static license which is problematic since we can change the licensing affecting old versions

2023-10-24 14:44 UTC, javidq commented on setup.py
> -    packages=find_packages(exclude=("tests", "docs", "examples")),
Missing in poetry setup

2023-10-24 14:44 UTC, javidq commented on setup.py
> -    package_data={"": ["_version.txt", "data/aoi_berlin.geojson", "data/aoi_washington.geojson"]},
Missing in poetry setup

2023-10-24 14:44 UTC, javidq commented on setup.py
> -    classifiers=[
Missing in poetry setup

2023-11-16 15:30 UTC, Geosynopsis reviewed
Commands to build, package, and upload are still using `setup.py` based instructions. Is it supposed to like that? Additionally, poetry supports [publishing](https://python-poetry.org/docs/libraries/#publishing-to-pypi). Using twine isn't necessary anymore.

2023-12-05 07:41 UTC, closed without merging