[AT-3970] enable pylint for estimation
up42/up42-py pull request #558
Opened 2024-03-12 13:03 UTC by seedlit

Jira ticket [here.](https://up42.atlassian.net/browse/AT-3970)
Scope: enable pylint for all estimation files

Items:
* [ ] Ran test & live-tests
* [ ] Implemented (new) unit tests
* [ ] Removed credentials
* [ ] Removed argument pointing to staging
* [ ] Updated [documentation](sdk.up42.com)

For release:
* [ ] Bumped version
* [ ] Added changelog
* [ ] Updated announcement banner

2024-03-12 14:11 UTC, janchrizz approved these changes
Approved for the live test removal of blocks estimation job, since it will be deprecated and we are not covering

2024-03-12 14:46 UTC, dustgalactic commented on CHANGELOG.md
> +**March 07, 2024**
```suggestion
## 0.37.0a4

**March 07, 2024**
```

2024-03-13 09:00 UTC, dustgalactic approved these changes

2024-03-13 13:27 UTC, javidq requested changes

2024-03-13 13:27 UTC, javidq commented on CHANGELOG.md
> +- Adjusted `estimate.py`, `test_estimate.py` and `fixtures_estimate.py` in accordance with Pylint checks.
estimate - estimation in all 3 cases

2024-03-13 13:29 UTC, javidq approved these changes

2024-03-13 13:32 UTC, merged