[PT-5505] ProductGlossary V2 get_collections
up42/up42-py pull request #656
Opened 2024-07-30 19:17 UTC by andher1802

See changelog.

Checklist:
* [ ] Test coverage
* [x] Version bump
* [x] Changelog update

2024-08-05 14:04 UTC, javidq requested changes

2024-08-06 08:52 UTC, andher1802 commented on up42/catalog.py
> +        sortby: Optional[utils.SortingField] = None,
waiting for confirmation from the backend team.

2024-08-06 09:28 UTC, andher1802 commented on up42/catalog.py
> +                            resolution_value=collection["metadata"].get("resolutionValue", None),
if we switch from the previous suggestion, this should not apply anymore.

2024-08-06 10:06 UTC, andher1802 commented on up42/catalog.py
> +                providers.extend(collection.providers)
can you be more specific?

2024-08-06 13:22 UTC, javidq approved these changes

2024-08-06 13:33 UTC, merged