[PT-5597] Fixing test for catalog clas
up42/up42-py pull request #671
Opened 2024-09-12 18:47 UTC by andher1802

See changelog.

Checklist:
* [x] Test coverage
* [x] Version bump
* [x] Changelog update

2024-09-12 18:49 UTC, andher1802 commented on tests/test_catalog.py
> -def test_construct_search_parameters_fc_multiple_features_raises(catalog_mock):
This is covered in test_utils and not related to catalog

2024-09-19 14:24 UTC, javidq requested changes

2024-09-19 14:24 UTC, javidq commented on up42/catalog.py
> +    session = base.Session()
Duplicate, not needed

2024-09-19 15:48 UTC, andher1802 commented on tests/test_catalog.py
> +Geometries = catalog.Geometries
Using directly the catalog.Geometry type triggers a pylint warning. Variable not allowed in type expressionPylance[reportInvalidTypeForm](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportInvalidTypeForm). We can add an ignore, remove the typing or add the typing alias as current.

2024-09-19 15:51 UTC, andher1802 commented on tests/test_catalog.py
> +    def output_directory(self, request, tmp_path) -> Optional[str]:
it is Generator[Path, None, None], a Path object.

2024-10-08 07:40 UTC, javidq requested changes

2024-10-08 07:40 UTC, javidq commented on tests/test_catalog.py
> +        download_folder = output_directory if output_directory else pathlib.Path.cwd() / "catalog"
`output_directory or pathlib.Path.cwd() / "catalog"`

2024-10-08 07:40 UTC, javidq commented on CHANGELOG.md
> +**Oct 7, 2024**
To be updated

2024-10-08 07:58 UTC, javidq approved these changes

2024-10-08 08:00 UTC, merged