[PT-5597] (4) `Catalog::construct_order_parameters` testing coverage
up42/up42-py pull request #676
Opened 2024-09-26 12:41 UTC by andher1802

See changelog.

Checklist:
* [x] Test coverage
* [x] Version bump
* [x] Changelog update

2024-09-26 12:51 UTC, andher1802 commented on tests/test_catalog.py
> +Geometry = catalog.Geometry
This one is due to a pylance issue, which does not allow to use imported variables in the test parameters typings.

2024-10-07 11:36 UTC, javidq requested changes

2024-10-07 11:36 UTC, javidq commented on tests/test_catalog.py
> +    catalog_obj = catalog.Catalog(auth=mock.MagicMock(), workspace_id=constants.WORKSPACE_ID)
Not needed, self.catalog doesn't shadow package name

2024-10-07 11:36 UTC, javidq commented on up42/catalog.py
> +        aoi: Optional[Geometry] = None,
Let's simplify the schema handling via initializing the params in advance

2024-10-07 11:36 UTC, javidq commented on tests/test_catalog.py
> +        assert schema_property in order_parameters["params"]
To be simplified to a single equality check via
```python
expected = {
            "params": {
                "id": image_id,
                schema_property: None,
                **({"aoi": aoi} if aoi else {}),
            },
            "dataProduct": constants.DATA_PRODUCT_ID,
            **({"tags": tags} if tags else {}),
        }
```

2024-10-07 11:36 UTC, javidq commented on tests/test_catalog.py
> +        schema_property = "any-property"
schema_property -> required_property

2024-10-07 11:36 UTC, javidq commented on tests/test_catalog.py
> +        order_parameters: order.OrderParams = catalog.Catalog(
typing hint is not needed here

2024-10-07 11:36 UTC, javidq commented on CHANGELOG.md
> +## 2.1.0a9
We don't need fixture_catalog any more

2024-10-07 13:10 UTC, javidq approved these changes

2024-10-07 13:10 UTC, merged