[PT-5671] Updating `base::get_credits_balance` from base.py
up42/up42-py pull request #683
Opened 2024-10-29 11:05 UTC by andher1802

See changelog.

Checklist:
* [x] Test coverage
* [x] Version bump
* [x] Changelog update

2024-10-30 09:44 UTC, javidq requested changes

2024-10-30 09:44 UTC, javidq commented on CHANGELOG.md
> +- Updating endpoint for `base::get_credits_balance` and adding `timestamp` as an optional parameter.
We can't add new functionality with patch version, let's drop the timestamp part

2024-10-30 09:44 UTC, javidq commented on up42/base.py
> +        url = host.endpoint("/v2/payments/balances")
This API hasn't been published yet

2024-10-31 12:30 UTC, andher1802 commented on up42/base.py
> +        url = host.endpoint("/v2/payments/balances")
It is published now. :)

2024-11-19 06:20 UTC, javidq approved these changes

2024-11-19 06:24 UTC, merged